name: Azure Static Web Apps Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Site
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact for deployment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"            # Site lives at the repo root
          api_location: ""             # You have no API folder
          output_location: "/"        # No separate build output directory
